Quesddo/Client

- .github/workflows/random-reviewer.yml
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-49)
<br/>
- target branch가 dev로 되어있어 develop에 PR 열릴 때 리뷰어 등록 안되던 버그 해결
- `dev => develop` 로 변경
<br/>
> fix: 랜덤리뷰어 workflow target branch 오타 수정

- src/styles/globals.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-54)
<br/>
- 디자인토큰 `text-lg`의 line-height가 "18px"로 잘 못 설정되어 있어 "28px"로 수정하였습니다.
<br/>
> fix(TODO-54): 디자인토큰 `text-lg`의 line-height 오타 수정 `18px => 28px`

- src/components/atoms/dropdown/dropdown.tsx
- views/notes/dropdown.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-74)
<br/>
- dropdown 컴포넌트를 공통컴포넌트로 분리하였습니다.
- 버튼의 내용과 클릭 시 동작을 직접 설정할 수 있도록 개선하였습니다.
- size를 넘겨주지 않으면 default로 `sm`이 적용됩니다.
``` tsx
const dropdownItems = [
{ label: "Edit", onClick: () => alert("Edit clicked") },
{ label: "Delete", onClick: () => alert("Delete clicked") },
{ label: "Share", onClick: () => alert("Share clicked") },
];
<Dropdown items={dropdownItems} size="md"  />
```
<br/>
> feat(TODO-74): Dropdown 공통 컴포넌트 분리 및 범용성 개선

- src/views/layouts/organisms/MenuGoal.tsx
- src/views/layouts/organisms/SidebarHeader.tsx
- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-78)
<br/>
- 하위 컴포넌트 MemoGoal에 memo 추가 적용했습니다.
- 작은 아이콘에 기존 next/image -> img 태그로 변경했습니다. 
<br/>
> refactor(TODO-78): 사이드바 리팩터링

- src/views/layouts/organisms/MenuDashBoard.tsx
- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-83)
<br/>
- 전역 content-box로 깨진 스타일 복구
- sm(태블릿) 사이즈에서 사이드바 닫혔을때 backdrop 제거 
<br/>
> style(TODO-83): 사이드바 스타일 수정

- src/types/types.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-90)
<br/>
- OAS generator에서 추출해온 params type에 teamId가 필수속성으로 지정되어있어 제거하였습니다.
<br/>
> chore(TODO-90): params type에 teamId 속성 제거

- src/styles/globals.css
- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-88)
<br/>
- 964px을 넘을 시 pc와 동일하게 사이드바가 동작하도록 수정했습니다.
- sm(태블릿) 과 md(PC) 크기 사이의 스타일 변수를 추가했습니다 
(smd : small + medium)
- sm 사이즈에서의 컨텐츠 영역(636px) + 사이드바 크기(280px) = 916px 
916px + x축 패딩(24px + 24px) = 964px
임을 고려하여 smd는 964px로 설정했습니다.
https://github.com/user-attachments/assets/07599671-ab50-4853-a92f-be4cfdf521ea
> style(TODO-88): sm 최소 컨텐츠 + 사이드바 오픈 일 때의 스타일 수정

- src/components/atoms/button/Button.tsx
- src/components/atoms/input/Input.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-92)
<br/>
- button 타입의 type 속성을 기본 button으로 수정했습니다.(form에서 Enter 입력 시 자동 제출 방지)
form의 button type 은 submit으로 넘겨주세요.
- input 의 `box-sizing: 'border-box'`로 수정했습니다.
<br/>
> chore(TODO-92): 공통 컴포넌트 스타일 및 속성 수정

- src/apis/apiClient.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-102)
<br/>
> 401 Unauthorized
> 서버 메시지 있을 때
> 메시지 없을 경우
<br/>
- 메시지 없을 경우는 신경 안 써도 되겠습니다!
> fix(TODO-102): Instance 에러 케이스 수정

- src/components/atoms/plus-icon/PlusIcon.stories.ts
- src/components/atoms/plus-icon/PlusIcon.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-111)
<br/>
- PlusIcon 컴포넌트를 구현했습니다.
- width, height의 기본값은 24로 크기를 수정하고 싶을 땐 props로 변경하면 됩니다.
- 색상은 부모 요소의 색상을 따라갑니다. 직접 부여하고 싶을 시엔 아래 두가지 중에서 선택하면 됩니다.
-  color props를 넘기기
-  className으로 text color값 넘기기 
```
// 색상 설정
<div className="text-blue-700" >
<PlusIcon />
</div>
<PlusIcon color="#2563eb" />
<PlusIcon className="text-blue-700" />
// 크기 설정
<PlusIcon width={16} height={16} />
```
<br/>
- Plus 이미지를 색상, 크기별로 다양하게 적용하는 곳이 많아 svg형태의 컴포넌트를 추가하는게 효율적이라고 생각해서 추가했습니다.
> feat(TODO-111): PlusIcon 컴포넌트 구현

- src/views/layouts/atoms/AddButton.tsx
- src/views/layouts/atoms/MenuItem.tsx
- src/views/layouts/molecules/GoalCreationForm.tsx
- src/views/layouts/molecules/TabSideMenuList.tsx
- src/views/layouts/organisms/MenuDashBoard.tsx
- src/views/layouts/organisms/MenuGoal.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-107)
<br/>
- 기존에 한 파일에 있던 내용을 컴포넌트로 분리했습니다. (AddButton, GoalCreationForm)
- input은 공통 컴포넌트 UI와 달라 적용하지 않았습니다.
- Input의 value를 state 적용하지 않고 form에서 처리할 수 있도록 변경했습니다.
<br/>
> feat(TODO-107): 컴포넌트 분리

- src/utils/formatDate/formatDate.test.ts
- src/utils/formatDate/formatDate.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-136)
<br/>
- 서버에서 `ISO 8601` 형식의 날짜 포맷을 반환해주어서 포매터가 필요할 것 같아 구현하였습니다.
- 기본적으로 `YYYY. MM. DD` 형식을 사용하며, 원하는 형식으로 변경할 수도 있습니다.
``` typescript
formatDate(new Date()); 
// "2025. 02. 19" (현재 날짜 기준)
formatDate(1708320000000); 
// "2024. 02. 19" (Timestamp 입력)
formatDate("2024-05-15", "YYYY/MM/DD"); 
// "2024/05/15" (다른 포맷 적용)
formatDate("2024-12-01", "MM-DD-YYYY"); 
// "12-01-2024" (월-일-연도 형식)
formatDate("2025-04-29T06:15:59.808Z"); 
// "2025. 04. 29" (ISO 8601 입력)
````
<br/>
> feat(TODO-136): 날짜 포맷 변환 함수 구현

- src/components/atoms/button/Button.tsx
- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-이슈번호)
<br/>
- 사이드바에서의 isOpen 상태의 기본값을 변경했습니다
- 모바일에서 빠르게 열렸다 닫히는 플리커 현상을 제거하기 위함
- 태블릿 이상의 크기에서 닫힘 -> 열림이 애니메이션으로 자연스럽게 처리됨
- Button 컴포넌트에 `box-sizing: border-box`를 적용했습니다.
- outline과 default의 크기가 border로 인해 다르기 때문
<br/>
> style(TODO-135): Sidebar 기본 open 상태 및 Button 컴포넌트 style 수정

- package.json
- pnpm-lock.yaml
- src/hooks/goal/useCreateGoal.ts
- src/hooks/goal/useIniniteGoals.ts
- src/views/layouts/molecules/GoalCreationForm.tsx
- src/views/layouts/molecules/TabSideMenuList.tsx
- src/views/layouts/organisms/MenuGoal.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-114)
<br/>
- 목표 데이터 가져오기 api 요청을 하위 컴포넌트로 이동(TabSideMenuList)
- 목표 추가 api 추가적인 콜백 수행 처리 추가(useCreateGoal - onSuccess, onError) 및 쿼리 데이터 무한 스크롤에 맞춰 수정
- 목표 데이터 무한 스크롤 가져오기 hooks 추가
<br/>
> feat(TODO-114): 목표 무한 스크롤 구현

- src/hooks/auth/useSign.ts
- src/pages/login/index.tsx
- src/pages/signup/index.tsx
- src/types/Sign.ts
- src/views/sign/Form.tsx
- src/views/sign/Input.stories.tsx
- src/views/sign/Input.tsx
- src/views/sign/LoginPage.stories.tsx
- src/views/sign/Modal.stories.tsx
- src/views/sign/SignupPage.stories.tsx
- src/views/sign/fieldSet.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-66)
<br/>
- 로그인/회원가입에 유효성 검사 기능을 추가했습니다.
- pages/login, signup에 있던 프롭들을 Form에 넘겨주었습니다.
- 서버 유효성 체크는 useSign 훅에서 처리합니다.
- 스토리북 파일을 추가했습니다.
- 유효성 체크를 이렇게 적용해도 괜찮을까요
> feat(TODO-66): 로그인/회원가입 유효성 체크 기능 구현

- src/apis/apiClient.ts
- src/hooks/auth/useSign.ts
- src/utils/tokenUtils.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-67)
- 로그인 성공한 경우 토큰을 저장
- axios에서 token이 있는 경우 토큰을 헤더에 설정하여 요청
-
> feat(TODO-67): 로그인 후 토큰 저장, axios 요청에 header 설정

- src/components/atoms/page-title/PageTitle.stories.ts
- src/components/atoms/page-title/PageTitle.tsx
- src/pages/_app.tsx
- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-144)
<br/>
- 페이지마다 필요한 Title을 컴포넌트화했습니다.
- 해당 컴포넌트의 `isMobileFixed` 속성을 통해 header에 둘지 여부를 선택할 수 있습니다.
-  이에 따라 기존 `Component.headerContent` 으로 지정하는 부분은 제거했습니다.
- [new🌟] sidebar 내부에서 pathname에 따라 hidden 결정
<br/>
- `isMobileFixed = false` (기본값) 
- `isMobileFixed = true`
> feat(TODO-144): PageTItle 컴포넌트 추가 및 sidebar 내부에서 pathname에 따라 hidden 결정

- src/apis/apiClient.ts
- src/apis/apiRefreshTokens.ts
- src/components/AuthGuard.tsx
- src/hooks/auth/useAuth.ts
- src/hooks/auth/useSign.ts
- src/pages/_app.tsx
- src/utils/tokenUtils.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-150)
<br/>
- 전역으로 사용되는 AuthGuard, 인증레이어 추가
- AuthGuard에서 useAuth 사용
- apiClient.ts에서 message의 값을 확인하여 토큰재발급
- 플로우를 다음과 같이 진행했는데 괜찮을까용??
- 비회원은 로그인과 회원가입 페이지만 접근가능, 나머지 접근 시 로그인으로 리다이렉트 됩니다.
- 회원은 투두 기능페이지 접근가능하며 로그인, 회원가입 접근 시 대시보드로 리다이렉트 됩니다.
> feat(TODO-150): 인증레이어 구현

- src/apis/note/deleteNote.ts
- src/apis/note/fetchNotes.ts
- src/hooks/note/useDeleteNote.ts
- src/hooks/note/useInfiniteNotes.ts
- src/pages/goal/[goalId]/notes/index.tsx
- src/views/notes/card/Card.stories.tsx
- src/views/notes/card/Card.tsx
- src/views/notes/empty-notes/EmptyNotes.tsx
- src/views/notes/note-list/NoteList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-160)
<br/>
- 노트 수정 및 삭제 기능을 구현했습니다.
- 노트 수정 시, `?noteId=<noteId>&mode=edit` 경로로 이동하여 edit 사이드바가 렌더링되도록 처리했습니다.
- 노트 삭제 시, 낙관적 업데이트를 적용하여 즉각적인 반영이 이루어지도록 했습니다.
- 노트 리스트의 무한 스크롤 반환값을 select 옵션을 활용해 flat하게 가공했습니다.
- 노트가 없는 경우를 고려하여 UI 예외 처리를 추가했습니다.
<br/>
https://github.com/user-attachments/assets/b8f8d349-6ed9-4e84-a4d4-2a4882775dae
<br/>
https://github.com/user-attachments/assets/8a1fda42-5391-4d60-a3f8-815992300a2c
<br/>
<br/>
- 로딩, 에러처리는 MVP 끝나면 추가하겠습니다 😢
> feat(TODO-160): [노트모아보기 페이지]  노트 수정, 삭제 기능 구현 및 리팩토링

- .storybook/preview.tsx
- src/components/atoms/action-dropdown/ActionDropdown.stories.tsx
- src/components/atoms/divider/Divider.stories.tsx
- src/components/atoms/exit-btn/ExitBtn.stories.tsx
- src/components/atoms/goal-item/GoalItem.stories.tsx
- src/components/atoms/page-title/PageTitle.stories.ts
- src/components/atoms/plus-icon/PlusIcon.stories.ts
- src/components/atoms/spinner/Spinner.stories.tsx
- src/components/atoms/todo-chip/TodoChip.stories.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-169)
<br/>
- 스토리북 전역에 설정되어있던 ` tags: ["autodocs"]` 을 제거하였습니다.
- 사유: docs 때문에 버그가 발생하는 스토리가 존재하여, 해당 스토리는 docs를 넣지 않으려다보니 전역에 있는 autodocs 설정을 제거해야 했습니다.
- docs가 필요할 경우 개별 스토리에 넣어주세요.
<br/>
> chore(TODO-169): [스토리북] 전역 autodocs 옵션 제거

- src/components/organisms/todo-list/TodoList.tsx
- src/hooks/todo/useInfiniteTodo.ts
- src/pages/todo/index.tsx
- src/styles/globals.css
- src/styles/slideUp.css
- src/views/dashboard/recent-todo/RecentTodo.tsx
- src/views/todo/todo-item/TodoItem.tsx
- src/views/todo/todoPage/Todos.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-186)
<br/>
- 할 일 목록 페이지에 `useSuspenseInfiniteQuery`사용한 훅으로 교체해 무한스크롤 구현
- 할 일 나올 때 부드럽게 올라오는 애니메이션 적용(기능요구사항)
<br/>
- 첫 페이지 이후의 **새 데이터(무한스크롤 시)에만 애니메이션 적용**은 좀 더 시간이 들 것 같아 추후 반영해보겠습니다.
> feat(TODO-186): [할 일 페이지] 무한스크롤

- .github/workflows/storybook.yml
- src/apis/apiClient.ts
- src/constants/env.ts
- src/mocks/note/noteHandlers.ts
- src/mocks/todo/todoHandlers.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-172)
<br/>
- PR 올릴 때 말고도, main브랜치를 기반으로 스토리북이 배포되도록 하였습니다.
- 스토리북에 환경변수 적용하였습니다.
- 환경변수를 `constants/env.ts`에서 관리하도록 수정  
- Next.js와 Storybook 환경변수를 모두 지원하도록 처리  
[[스토리북] 환경변수 적용에 관한 이슈](https://instinctive-linseed-8cb.notion.site/1aa8a37bf8a280eda5bbdd786651d1e8?pvs=4)
<br/>
- MSW 핸들러 구축 시에 `process.env.NEXT_PUBLIC_API_BACKEND_URL`로 직접 backend url 가져오지 말고, `constants/env.ts` 에 정의된 `API_BACKEND_URL` 을 사용해주세요.
``` ts
// mocks/note/noteHandlers.ts
import { API_BACKEND_URL } from "@/constants/env";
export const noteHandlers = [
http.get(`${API_BACKEND_URL}notes/:noteId`, ({ params: { noteId } }) => {
...
```
> chore(TODO-172): [스토리북] main 기반 스토리북 배포 및 환경변수 적용

- src/apis/note/fetchNotes.ts
- src/hooks/note/useInfiniteNotes.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-198)
<br/>
- useInfiniteQuery에서 첫 호출 시 cursor가 0이 들어가는 버그가 발생하였습니다.
- 초기값이 `0 => undefined` 가 되도록 수정하여 해결하였습니다.
<br/>
> fix(TODO-198): [노트 무한스크롤] 초기 cursor가 0으로 들어가는 버그 수정

- src/components/organisms/todo-list/todoList.stories.tsx
- src/hooks/goal/useFetchGoals.ts
- src/mocks/todo/todoMockData.ts
- src/pages/todo/index.tsx
- src/views/todo/TodoForm.tsx
- src/views/todo/todo-item/TodoItem.tsx
- src/views/todo/todo-item/todoItem.stories.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-207)
<br/>
- suspense만 적용되어있던 부분에 BoundaryWrapper 사용
- 할 일 목록 폼에서 일반 목록으로 불러오는 목표 최대 갯수 50으로 설정
- 할 일 목록 폼 title 글자 수 maxLength 제한 추가
- 할 일 목록 호버아이콘 터치 환경에서 마우스 커서포인터 추가
<br/>
- hover해야 나오는 아이콘을 지금은 터치 환경에서 할일li 클릭하면 나오도록 해뒀는데.. 모든 환경에서 그렇게 되도록 해도 될 것 같다는 생각이 듭니다(클릭 시 hover 정지)
- spinner를 세로 중앙에 배치하고 싶으면 어떻게 해야할까요? 부모 레이아웃을 건드리기엔 제약이 있어서
> refactor(TODO-207): 할 일 목록페이지 BoundaryWrapper 적용

- src/hooks/goal/useDeleteGoal.ts
- src/hooks/goal/useUpdateGoal.ts
- src/pages/goal/[goalId]/index.tsx
- src/views/goal/component/GoalHeader.tsx
- src/views/goal/component/GoalSection.tsx
- src/views/goal/component/NoteSection.tsx
- src/views/goal/component/Section.tsx
- src/views/goal/component/TodoListSection.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-204)
- 목표 수정/삭제 시 사이드바의 내용과 다른부분을 수정했습니다.
- 할일/끝낸일의 스크롤 꽉 막힌 부분을 조금 수정했습니다.
- 기타
- 컴포넌트 분리/위치 이동
- 네이밍 수정
> fix(TODO-204): 목표 상세 페이지 목표를 수정/삭제 시 사이드바와 맞지 않는 부분 수정

- src/components/organisms/note-detail/components/NoteDetailContent.tsx
- src/views/note/editor/ReactQuillEditor.tsx
- src/views/note/note-form/Editor.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-210)
<br/>
- 노트 상세에 editor 라이브러리(react-quill)를 사용
- 노트 작성/수정과 컨텐츠 스타일이 동일하도록 수정하였습니다.
- 태그가 나오는 문제 처리
<br/>
- 적용된 이미지
> feat(TODO-210): [노트 상세] 노트 내용에 editor 라이브러리 적용

- src/apis/todoApi.ts
- src/hooks/todo/useTodos.ts
- src/types/todo.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-215)
<br/>
- 할 일 데이터를 "todo", "done" 에 따라 필터링하여 받아와야할 필요가 생겨, filter 인자를 넣어줄 수 있도록 확장하였습니다.
- filter를 넣어주지 않으면 완료 여부와 관계 없이 모든 할 일을 불러옵니다.
- useTodos에서 queryFn을 API 폴더로 분리하였습니다.
<br/>
> feat(TODO-215): [useTodos] 완료 여부에 따라 할 일 필터링하여 받아오도록 확장

- src/hooks/note/useAutoSaveNoteDraft.ts
- src/hooks/note/useNoteDraft.ts
- src/hooks/note/useNoteStorage.ts
- src/views/note/editor/ReactQuillEditor.tsx
- src/views/note/note-drawer/NoteDrawer.tsx
- src/views/note/note-form/DraftNoteReminderToast.tsx
- src/views/note/note-form/Editor.tsx
- src/views/note/note-form/LinkModal.tsx
- src/views/note/note-form/NoteCreationForm.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- src/views/note/note-form/TitleWithCounter.tsx
- src/views/note/note-form/utils/noteStorage.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-208)
<br/>
- 임시저장
- 불러오기 시 임시저장 제목 관련 팝업 모달 추가
- 노트 작성/수정 완료 시 임시저장 노트는 제거
- localStorage + Interval 처리가 함께 있던 hooks 분리
- 하나의 노트만 저장되던 오류 처리
- 토스트가 두 번 불러지는 오류 처리
- NoteDrawer에 있던 InputProvider 제거 (최상단 컴포넌트에 있기 때문)
- 컬러 팔레트 위치 조정
<br/>
> feat(TODO-208): [노트 작성/수정] 임시저장 workflow 개선

- src/views/todo/todo-update-form/TodoUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-224)
<br/>
- MVP 피드백에서 언급된 지저분한 코드 리팩토링
- 조건문 간략하게 수정
- 의존성 배열에서 생략해도 안전할 함수들 제거
<br/>
- useEffect를 다른 방법으로 바꿔보려 했지만, useQuery에서 onSuccess 옵션이 아예 제거된 이슈도 있고 useMemo로 바꾸어도 문제가 있어서 최대로 정리를 해보았습니다. 더 좋은 방법이 있다면 좋겠네요!
> refactor(TODO-224): [할 일 수정폼] useEffect에서 상태설정 - 개선 시도

- src/contexts/GoalDetailContext.tsx
- src/hooks/goal/useDeleteGoal.ts
- src/hooks/todo/useInfiniteTodo.ts
- src/pages/goal/[goalId]/index.tsx
- src/views/goal/header/Progress.tsx
- src/views/goal/todo/GoalDoneList.tsx
- src/views/goal/todo/GoalTodoContainer.tsx
- src/views/goal/todo/GoalTodoList.tsx
🔗 연관된 이슈
[연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-220)
📗 작업 내용
- 목표상세 무한스크롤 기능 추가
- todo list, done list 분리
- 레이아웃 수정
- progress 계산방식에서 api로 변경
- 할일 추가를 했을 때 할일의 totalCount 수가 변경되어 api방식이 나은것으로 판단
💬 리뷰 요구사항(선택)
- 무한스크롤의 기능 동작은 하는데 원하는 동작인지는 모르겠네요.
- 데이터 전처리는 다음 PR에 진행할 예정입니다.
> feat(TODO-220): 목표상세 무한스크롤 기능

- src/apis/goalApi.ts
- src/hooks/goal/useInfiniteGoals.ts
- src/hooks/goal/useSidebarInfiniteGoals.ts
- src/views/todo/TodoForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-231)
<br/>
- 무한 스크롤에서 쿼리 키가 겹쳐 데이터 크기 및 `fetchNextPage`에서 버그가 발생하는 문제를 해결하기 위해, 쿼리 키를 개별적으로 관리하도록 수정하였습니다.  
- `useInfiniteGoals` 함수 호출 시 `size`와 `source`를 인자로 받을 수 있도록 변경하였습니다.  
- `source`는 `"sidebar"`, `"dashboard"`, `"todoForm"`이며, 각각의 쿼리 키에 추가됩니다.
<br/>
> refactor(TODO-231): [useInfiniteGoals] 필요한 파트마다 쿼리키 개별적으로 관리하도록 수정

- src/apis/fileApi.ts
- src/hooks/todo/form/useTodoForm.ts
- src/views/goal/todo/GoalTodoContainer.tsx
- src/views/goal/todo/GoalTodoList.tsx
- src/views/todo/todo-create-form/TodoCreateForm.tsx
- src/views/todo/todo-update-form/TodoUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-213)
<br/>
- 자식 컴포넌트에서 id를 받아오느라 목표 상세에 상태가 하나 추가되었습니다. 
- 기존 목표값 세팅하면서 변경되는 폼 파일과 훅 수정하면서 리팩토링도 조금씩 해봤습니다.
(코드리뷰 받은 상태처리/UI폼 로직 분리건, fileApi 클래스로 캡슐화)
<br/>
- 목표 상세에 코드가 복잡해졌습니다.. 할일 모달 관련 로직 리팩토링.. 예정~.~
> refactor(TODO-213): 목표 상세에서 할 일 생성 시 기존 목표 세팅

- src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
- src/views/dashboard/goal-based-todo/components/GoalItem.tsx
- src/views/dashboard/goal-based-todo/goal-based-todo.md
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-217)
<br/>
- 대시보드의 목표별 할 일 에서 목표 무한스크롤 구현하였습니다.
https://github.com/user-attachments/assets/e0c0901d-730c-41e8-ae7c-32f6aaae6516
<br/>
-  현재 PR 검토중인 `TODO-231`의 코드가 필요해서 가져다 사용했는데, 이번 PR에서 `TODO-217`의 변경사항만 보여주기 위해서 `TODO-217 -> TODO-231`로 올립니다. `TODO-231`이 main으로 merge되면 이 PR도 main으로 수정하여 merge 하겠습니다 !
> feat(TODO-217): [대시보드/목표별 할 일] 목표 무한스크롤 구현

- src/views/layouts/sidebar/Sidebar.stories.tsx
- src/views/layouts/sidebar/Sidebar.tsx
- src/views/layouts/sidebar/components/CloseSidebarLink.tsx
- src/views/layouts/sidebar/components/MenuDashBoard.tsx
- src/views/layouts/sidebar/components/SidebarHeader.tsx
- src/views/layouts/sidebar/components/goals/TabSideMenuItem.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-227)
<br/>
- 사이드바를 통해 링크 이동 시, 사이드바가 닫히도록 처리했습니다.
- SMD 크기부터 열림 고정 처리
<br/>
> feat(TODO-227): 모바일 사이드바 링크 클릭 시 닫힘 처리 및 SMD 크기부터 열림 고정

- package.json
- pnpm-lock.yaml
- src/hooks/todo/useProgressTodo.ts
- src/styles/gauge.css
- src/styles/globals.css
- src/views/dashboard/my-progress/MyProgress.tsx
- src/views/dashboard/my-progress/components/Gauge.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-209)
- 대시보드 진행상황 추가
- 먼가 배경에 이미지있으면 좋을것 같은데  심심하군요.
- 감사합니다.
> feat(TODO-209): 대시보드 진행상황 추가

- src/hooks/auth/useSign.ts
- src/views/sign/Input.stories.tsx
- src/views/sign/SignForm.tsx
- src/views/sign/SignInput.tsx
- src/views/sign/SignPage.stories.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-236)
- 로그인/회원가입에서 input의 change이벤트로 유효성 검증하던것을 react-hook-form의 onChange로 변경했습니다.
- 유효성 검사시점을 패키지 내부에서 관리
- 기타
- 네이밍 수정
- 이상한 로직 수정
- 더 좋은 방법이 있을까요??
> refactor(TODO-236): 로그인/회원가입 리렌더링 이슈

- src/components/organisms/note-detail/NoteDetail.tsx
- src/pages/goal/[goalId]/index.tsx
- src/pages/goal/[goalId]/notes/index.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-232)
<br/>
- 노트 모아보기 및 목표 상세 페이지에서 SMD 사이즈일 때 사이드바에 의해 컨텐츠가 가려지는 현상을 수정했습니다.
- 레이아웃을 조정하여 사이드바와 컨텐츠가 정상적으로 표시되도록 개선했습니다.
> chore(TODO-232): [노트모아보기, 목표상세] SMD 사이즈에서 사이드바에 가려지는 문제 해결

- src/pages/goal/[goalId]/index.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-224)
<br/>
- 목표상세페이지에서 배경 밖으로 컨텐츠가 튀어나오는 레이아웃을 수정하였습니다.
<br/>
> chore(TODO-224): [목표상세] 배경 밖으로 컨텐츠 튀어나오는 부분 수정

- src/styles/gauge.css
- src/views/dashboard/my-progress/MyProgress.tsx
- src/views/dashboard/my-progress/components/Gauge.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-248)
<br/>
- 게이지 굵기를 키웠습니다.
- 레이블의 색 변경
- 타이틀의 크기 변경
- 두번째 여백 이미지입니다.
https://github.com/user-attachments/assets/abaad040-a33b-4709-931b-3ca7f132e199
> style(TODO-248): 대시보드 진행상황 스타일링 1차수정

- src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-255)
<br/>
- 스크롤 감지 블럭에 height를 지정하여 인지하지 못하는 문제 방지
- inView의 값의 변화로 useEffect의 조건문이 적용되며 한 페이지 이상의 데이터를 가져오는 문제를 
스크롤 감지 블럭에 조건을 적용하여 해결
<br/>
> fix(TODO-255): 사이드바 목표 무한 스크롤 오류 처리

- src/hooks/todo/useTodos.ts
- src/views/dashboard/goal-based-todo/components/TodoWrapper.tsx
- src/views/dashboard/recent-todo/RecentTodo.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-219)
<br/>
1. **대시보드 최근 등록한 할 일 목록 최적화**  
- 기존: 최근 등록한 할 일 목록을 20개 가져옴  
- 변경: 5개만 가져오도록 개선하여 불필요한 데이터 로드 방지  
<br/>
2. **`useTodo` 매개변수 개선**  
- 기존: `useTodo` 훅의 매개변수가 3개로 개별 전달됨  
- 변경: 객체 형태로 받아 가독성과 확장성을 향상  
<br/>
> refactor(TODO-219): 대시보드 - 최근 등록한 할 일 최적화 및 useTodo 매개변수 개선

- src/apis/noteApi.ts
- src/hooks/note/useFetchNote.ts
- src/pages/_app.tsx
- src/views/note/note-detail/components/EmbeddedContent.tsx
- src/views/note/note-detail/components/LinkItem.tsx
- src/views/note/note-detail/components/NoteDetailContent.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-192)
<br/>
1. **API 호출 함수 통합**  
- 기존: 기능이 겹치는 `fetchNote`와 `fetchNoteDetail` 두 개의 API 호출 함수 존재  
- 변경: `fetchNote` 하나로 통합하여 중복 제거 및 코드 간소화  
<br/>
2. **`fetchNote` 로직 훅으로 분리**  
- 기존: `fetchNote` 관련 로직이 컴포넌트 내부에 분산되어 있음  
- 변경: `useFetchNote` 훅으로 분리하여 코드 재사용성을 높임
<br/>
> refactor(TODO-192): `fetchNote` API 함수 통합 및 `useFetchNote` 훅 분리

- src/components/organisms/modal/InputModal.tsx
- src/views/todo/input-dropdown/InputDropdown.tsx
- src/views/todo/input-dropdown/InputDropdownItem.tsx
- src/views/todo/todo-form/TodoForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-258)
<br/>
- 기존 목표가 첫페이지에 없을 때 스크롤을 내려서 불러오고 나서야 해당 값이 뜨게 돼서 무한스크롤 제거하려고 합니다.
- 선택된 항목 표시
<br/>
- 목표값 설정을 아예 다른 방식으로 하는 수 말곤 모르겠네요🤔 받아오는 데이터와는 무관하게 보여주기?
> fix(TODO-258): 할일폼 목표드롭다운 무한스크롤 제거

- src/pages/todo/index.tsx
- src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
- src/views/dashboard/my-progress/MyProgress.tsx
- src/views/dashboard/recent-todo/RecentTodo.tsx
- src/views/todo/todoPage/TodoPage.stories.tsx
- src/views/todo/todoPage/Todos.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-263)
<br/>
- 전에 스토리북 빌드오류로 임시제거했던 할일페이지 스토리북 재투입
- 겸사겸사 페이지 UI 조정 (필터버튼 옆 항목개수, 스피너 위치)
- 겸사 대시보드 박스들 padding값 일치
<br/>
> style(TODO-263): [할일 목록페이지] 스피너 위치 조정 및 스토리북 부활

- src/pages/dashboard/index.tsx
- src/views/dashboard/recent-todo/RecentTodo.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-268)
<br/>
- RecentTodo 부모에서 에러, 로딩 처리
- 기본으로 `가장 최근에 추가한 할 일`, `진행률`이 전체의 50%의 width를 가지도록 스타일 수정
<br/>
노션에 관련 글 추가했습니다.
- [노션 바로가기](https://www.notion.so/Suspense-1b58a37bf8a2803788eacfeee67a89ea?pvs=4)
> fix(TODO-268): 느린 인터넷 환경에서 로그인 된 사용자가 루트 접속 시 빈화면 보이는 현상 처리

- src/hooks/note/useAutoSaveNoteDraft.ts
- src/hooks/note/useBlockNavigation.ts
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/components/Editor.tsx
- src/views/note/note-form/components/EditorTextCounter.tsx
- src/views/note/note-form/utils/checkEmptyNote.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-267)
<br/>
- 노트 작성 중 빈 노트인 경우 페이지 이동 모달이 나타나지 않도록 처리했습니다.
- 빈 노트인 경우 임시 저장을 하지 못하도록 처리했습니다.
<br/>
> feat(TODO-267): [노트 작성/수정] 임시 저장 및 페이지 이동 예외 처리

- src/views/notes/card/Card.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-273)
<br/>
- 노트모아보기 페이지에 카드 hover 시 shadow 적용하였습니다.
<br/>
> style(TODO-273): [노트 모아보기] 카드 hover시 shadow 적용

- src/components/organisms/toaster/Toaster.tsx
- src/views/layouts/sidebar/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-277)
<br/>
- 모바일에서 Toast가 보이지 않아 아래 작업을 진행했습니다.
- 전역(_app.tsx)에 있는 Toaster 컴포넌트의 스타일을 sticky에서 fixed로 수정
- 사이드 바에 있는 Toaster 컴포넌트의 스타일을 sticky에서 absolute로 수정
<br/>
> style(TODO-277): Toaster 스타일 수정

- src/hooks/note/useAutoSaveNoteDraft.ts
- src/views/note/note-create-form/NoteCreateForm.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/utils/checkEmptyNote.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-275)
<br/>
- 기존에는 노트 작성 중 페이지 이동 시 빈 노트이면 페이지 이동 모달을 띄우지 않았으나,
- 한 번이라도 입력을 했던 경우에는 페이지 이동 모달을 띄우도록 수정했습니다.
<br/>
> refactor(TODO-275): [노트 작성] 노트 작성 시도가 있었던 경우 페이지 이동 시 모달 open

- src/pages/_app.tsx
- src/pages/_document.tsx
- src/views/layouts/sidebar/components/goals/GoalCreationForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-282)
<br/>
- 전체 레이아웃을 모바일 스크린에도 맞도록 수정
- 모바일에서 body 와 content 스크롤바가 중첩되어, body 스크롤바 제거
- 모바일에서 목표 입력 시 스크린이 확대되지 않도록 폰트 사이즈 수정
<br/>
> style(TODO-282): [전체 레이아웃] 모바일 레이아웃에 맞춰 수정 및 목표 입력 스타일 수정

- src/components/atoms/action-dropdown/ActionDropdown.test.tsx
- src/components/atoms/action-dropdown/ActionDropdown.tsx
- src/components/atoms/button/Button.test.tsx
- src/components/atoms/exit-btn/ExitBtn.test.tsx
- src/components/atoms/exit-btn/ExitBtn.tsx
- src/components/atoms/goal-item/GoalItem.test.tsx
- src/components/atoms/goal-item/GoalItem.tsx
- src/components/atoms/input/Input.test.tsx
- src/components/atoms/input/Input.tsx
- src/components/atoms/spinner/Spinner.tsx
- src/components/atoms/title-with-icon/TitleWithIcon.tsx.tsx
- src/utils/formatDate/formatDate.test.ts
- src/views/dashboard/goal-based-todo/components/GoalItem.tsx
- src/views/note/note-detail/components/LinkItem.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-280)
<br/>
- 공통컴포넌트 일부 테스트코드 작성하였습니다.
<br/>
- 공통컴포넌트 다 하고 올리려다가 codecov 작동 확인하기 위해 일단 PR 올려봅니당
> test(TODO-280): 공통컴포넌트 일부 테스트코드 작성

- src/components/atoms/page-title/PageTitle.test.tsx
- src/components/atoms/plus-icon/PlusIcon.test.tsx
- src/components/atoms/plus-icon/__snapshots__/PlusIcon.test.tsx.snap
- src/components/atoms/progress-bar/ProgressBar.tsx
- src/components/atoms/todo-chip/TodoChip.test.tsx
- src/components/molecules/popup/Popup.test.tsx
- src/components/molecules/popup/Popup.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-280)
<br/>
- 공통컴포넌트 테스트코드 작성하였습니다.
<br/>
> test(TODO-280): 공통컴포넌트 테스트코드 작성
