- eslint.config.mjs
- src/apis/apiClient.ts
- src/hooks/useAxios.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-24)
<br/>
- API BASE URL 설정과 interceptors 세팅
- 에러, 로딩 분기처리를 할 수 있는 커스텀 훅 구현
<br/>
<hr/>
- API URL을 .env 파일에 세팅해주세요
`NEXT_PUBLIC_API_BACKEND_URL=API주소/quesddo/`
- 훅 사용 예시
```
import { useAxios } from "@/hooks/useAxios";
// 데이터 타입 정의
interface TComponent {
id: number;
title: string;
createdAt: string;
}
export default function Component() {
// useAxios 훅 호출하여 요청
const { data, isLoading, handleRequest, error } = useAxios<TComponent[]>({
url: "goals", // BASE_URL 제외한 API 엔드포인트
method: "post", // HTTP 메소드
initialData: [], // 초기 데이터 값 (빈 배열 등 맞게 설정)
shouldFetchOnMount: true, //  컴포넌트가 마운트될 때 호출할 필요가 있으면 true(get), 아니라면 false(post, put, delete)
});
const addGoal = () => {
// POST 요청 body 데이터
const newGoal = {
title: "새 목표",
createdAt: new …
```
> chore(TODO-24): axios 커스텀 훅

- package.json
- pnpm-lock.yaml
-
- React-hook-form 설치
- 패키지 설치했습니다.
> chore: react-hook-form 설치

- .prettierrc
- package.json
- pnpm-lock.yaml
- src/utils/cn.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-48)
<br/>
- tailwind utility 자동 정렬
- 조건/상태 변경에 따른 utility 덮어쓰기
<br/>
<hr/>
- className에 스타일 적용 예시
```
import { cn } from '@/utils/cn';
...
const [isBlue, setIsBlue] = useState(false);
<div className={cn('p-5 bg-red-100', isBlue && 'bg-blue-100')}>
box
</div>
```
- 지정된 스타일 조건에 따른 컴포넌트 제작 예시
```
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/cn";
const buttonVariants = cva(
"inline-block rounded",
{
variants: {
variant: {
default: "bg-blue-100 text-white",
outline: " border border-gray-2 bg-white",
},
size: {
default: "px-4 py-2",
sm: "h-[38px] w-[148px]",
lg: "w-[428px] h-[68px]",
},
},
defaultVariants: {
variant: "default",
size: "default",
},
},
);
export interface ButtonProps
extends …
```
> chore: tailwind 관련 라이브러리 추가 및 설정

- src/components/atomic/Input.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-52)
<br/>
- Input 컴포넌트 구현
<br/>
> feat(TODO-52): input 컴포넌트 구현

- src/styles/globals.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-50)
<br/>
- 반응형 breakpoint 설정하였습니다.
```
- sm(mobile => tablet) : 375px
- md(tablet => PC) : 744px
```
<br/>
> style(TODO-50): 반응형 breakpoint 설정

- .github/workflows/vercel-deploy.yml
- build.sh
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-13)
<br/>
- vercel 프리티어에서 팀프로젝트 배포 우회를 위해 개인레포와 sync를 맞추는 작업을 자동화하였습니다.
- [배포된 레포지토리 링크 🔗](https://github.com/thgee/Quesddo_Deploy)
- [배포주소 🔗](https://quesddo-deploy.vercel.app/)
<br/>
> chore(TODO-13): vercel 배포를 위한 sync 자동화 파이프라인 구축

- src/styles/globals.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-58)
<br/>
- `content-box` 가 익숙하여 합의 후 global.css 수정하였습니다.
<br/>
> style(TODO-58): global.css에 `box-sizing: content-box` 추가

- .github/workflows/develop-push.yml
- .github/workflows/main-pull-request.yml
- .github/workflows/main-push.yml
- .github/workflows/random-reviewer.yml
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-61)
<br/>
- 기존에 main, dev에 적용되던 랜덤 리뷰어지정 기능을 main, feature로 변경하였습니다. ([테스트 완료](https://github.com/Quesddo/Client/pull/27))
- main, dev 브랜치에 기본적인 CI 파이프라인을 구축하였습니다.
<br/>
> chore(TODO-61): feature에 랜덤리뷰어 적용 및 main, dev에 기본적인 CI구축

- .lintstagedrc.js
- 
<br/>
- 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)
- 커밋 시 lintstagedrc에서 발생하는 에러
- 에러화면
- 수정한 부분
```js
/* eslint-disable @typescript-eslint/no-require-imports */
const path = require("path");
```
> chore: .lintstagedrc.js 수정

- .gitignore
- src/types/types.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-69)
<br/>
- OAS generator 도입하여 API 타입을 추출하였습니다.
- Swagger의 schema 탭을 참고하여 필요한 타입을 import하여 사용합니다.
<br/>
> chore(TODO-69): OAS generator 도입하여 API 타입 추출

- src/styles/globals.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-72)
<br/>
- breakpoint를 아래와 같이 변경했습니다.
default(모바일) : ~ 744px
sm(태블릿)        : 744px ~ 1520px
md(PC)             :  1520px ~
<br/>
> feat(TODO-72): breakpoint 수정

- .husky/commit-msg
- .husky/pre-commit
- .lintstagedrc.js
- package.json
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-71)
<br/>
- lint, tsc, test 모두 staged된 변경사항만 실행되도록 수정하였습니다.
- husky 중복된 설정코드 통합 및 보일러플레이트 제거하였습니다.
<br/>
- 허스키 관련 버그 터지면 바로 알려주세요...
> chore(TODO-71): [husky] staged된 변경사항만 실행되도록 수정

- src/components/atoms/TodoCheckbox.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-77)
<br/>
- 체크 박스 간격이 피그마와 달라 추가했습니다! `mr-2`
> 수정 전
> 수정 후
<br/>
> style(TODO-77): 할 일목록 리스트 컴포넌트 스타일 미세 수정

- .github/workflows/merge-main-to-dev.yml
- .husky/pre-commit
- .lintstagedrc.js
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-75)
<br/>
- 허스키 타입체크 아예 빼는방향으로 수정하였습니다. 예상치 못한 버그가 너무 많네요
- main에서 dev로 자동merge 방식을 rebase에서 일반merge로 변경하였습니다.
<br/>
- 브랜치이름 실수로 잘 못 만들었네요.. ㅎ 죄송함다 😥
> chore(TODO-75): 허스키 롤백 및 main=>dev merge 로직수정

- .github/workflows/storybook.yml
- .storybook/main.ts
- .storybook/preview.ts
- package.json
- pnpm-lock.yaml
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-76)
<br/>
- PR시 스토리북 배포가 자동화되고, comment로 배포링크를 띄워줍니다.
- 이제 PR 단계에서 구현된 컴포넌트를 시각적으로 확인할 수 있습니다.
<br/>
> chore(TODO-76): 스토리북 배포 자동화

- src/hooks/goal/useCreateGoal.ts
- src/hooks/goal/useFetchGoals.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-80)
<br/>
- 목표 생성/가져오기 hooks 구현
<br/>
- 다른 페이지에서도 쓰이는 것 같아 hooks만 먼저 main으로 PR 올립니다.
> feat(TODO-80): 목표 생성/가져오기 hooks

- src/views/layouts/template/Sidebar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-이슈번호)
<br/>
- sidebar 태블릿 환경에서 처음 화면 접속시 close 상태로 수정했습니다.
<br/>
> style(TODO-103): sidebar 태블릿 환경에서 기본 close

- src/components/atoms/todo-checkbox/todoCheckbox.test.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-93)
<br/>
- 정말 작은 기능 테스트 시도
<br/>
- 스토리북에 체크되는 액션을 안 넣어놔서 테스트로 해보았습니다.
> test(TODO-93): 할 일 체크토글 유닛테스트

- src/views/layouts/atoms/MenuItem.tsx
- src/views/layouts/molecules/TabSideMenuList.tsx
- src/views/layouts/organisms/MenuGoal.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-82)
<br/>
- 사이드 바 목표 api 연동
<br/>
- 로딩은 no throttling 환경에서 플리커 현상을 고려하여 따로 적용하진 않았습니다.
(no throttling: 약 50ms, 3G: 약 2s)
필요 시 추가 적용하도록 하겠습니다~
> feat(TODO-82): 사이드 바 목표 api 연동

- src/hooks/user/useFetchUser.ts
- src/views/layouts/organisms/Profile.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-86)
<br/>
- 사이드바 회원정보 api 연동
<br/>
- 로딩은 no throttling 환경에서 플리커 현상을 고려하여 따로 적용하진 않았습니다.
필요 시 추가 적용하도록 하겠습니다~
- 로그아웃은 토큰 방식이 정해진 후에 적용하도록 하겠습니다.
> feat(TODO-86): 사이드바 회원정보 api 연동

- views/notes/card/card.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-119)
<br/>
- API 연동을 위해 Card 컴포넌트의 Content 부분을 더욱 세분화하였습니다.
<br/>
> refactor(TODO-119): Card 컴포넌트 구조 세분화

- .github/workflows/storybook.yml
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-126)
<br/>
- PR의  스토리북 preview가 feature/base 에만 적용되고 있었는데,  모든 feature브랜치에 적용되도록 수정하였습니다.
<br/>
> chore(TODO-126): [CI/CD] pr시 스토리북이 모든 feature브랜치에 적용되도록 수정

- views/notes/card/card.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-119)
<br/>
- API 연동을 위해 Card 컴포넌트의 Content 부분을 더욱 세분화하였습니다.
<br/>
> refactor(TODO-119): [Card 컴포넌트] 구조 세분화

- src/pages/_app.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-141)
<br/>
- 사이드바 노출하지 않는 경로 추가
-
> feat(TODO-141): 사이드바를 노출하지 않는 경로 추가

- src/styles/globals.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-154)
<br/>
- 모든 button 태그에 `cursor-pointer` 스타일 추가하였습니다.
<br/>
> style(TODO-154): button 태그에 `cursor-pointer` 스타일 추가

- package.json
- pnpm-lock.yaml
- src/views/note-creation-form/Editor.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-155)
<br/>
- react-quill-new 설치
- react-quill-new 라이브러리에 react-hook-form 적용
<br/>
> feat(TODO-155): react-quill-new 라이브러리 설치 및 적용

- src/views/notes/card/Card.stories.tsx
- src/views/notes/card/Card.tsx
- src/views/notes/goal/Goal.tsx
- src/views/notes/note-list/NoteList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-152)
<br/>
- 기존에 개별적으로 구현된 컴포넌트들을 공통 컴포넌트에서 가져와 사용하도록 개선했습니다.
<br/>
> chore(TODO-152): [노트 모아보기] 기존 코드에 공통컴포넌트 적용

- src/views/notes/card/Card.stories.tsx
- src/views/notes/card/Card.tsx
- src/views/notes/note-list/NoteList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-170)
<br/>
- 노트 클릭 시 노트상세보기 사이드바 렌더링되도록 구현하였습니다.
<br/>
> feat(TODO-170): [노트 모아보기] 노트 클릭 시 노트 상세보기 사이드바 렌더링

- src/apis/todoApi.ts
- src/hooks/note/useCreateNote.ts
- src/hooks/note/useNoteDraft.ts
- src/hooks/note/useUpdateNote.ts
- src/views/note/note-form/GoalTodoDisplay.tsx
- src/views/note/note-form/NoteCreationForm.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-166)
<br/>
- 목표, ToDo를 위한 todo api 연결
- 에러 처리 추가
- 잘못된 hooks 함수명 수정(파스칼 -> 카멜)
- 노트 생성/수정 후 무효화 추가
<br/>
> feat(TODO-166): 목표, ToDo를 위한 api 연결

- src/hooks/auth/useSign.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-이슈번호)
<br/>
- 대시보드 리다이렉트 하는 방식 변경했습니다.
-
> feat(TODO-174): 로그인 페이지 이동 기능변경

- src/pages/todo/index.tsx
- src/views/dashboard/recent-todo/RecentTodo.tsx
- src/views/todo/todo-item/TodoItem.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-175)
<br/>
- 에러 화면은 뜨지않게 잡았습니다. 기능은 여전히 되다 안되다..
- 각 할 일 아래 목표 안보일 수 있게 추가 했습니다.
<br/>
> feat(TODO-175): 할 일 목록 기능 빈데이터 디버깅

- src/pages/todo/index.tsx
- src/views/todo/todo-item/action-icon/ActionIcon.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-177)
<br/>
- router.push 해서 이동
- 사이드바 빠진 여백 재설정
<br/>
- 급한 불 먼저 끕니다!
> feat(TODO-177): 할 일 목록에서 노트 상세/생성 페이지 이동

- src/hooks/auth/useSign.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-176)
<br/>
- 라우터 푸쉬를 안하고 useAuth으로 리플레이스 시켰습니다.
-
> fix(TODO-176): push기능에서 refetch 방식으로 변경

- src/views/layouts/sidebar/components/Profile.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-178)
<br/>
- 로그아웃 기능 추가했습니다.
<br/>
> feat(TODO-178): 로그아웃 기능 추가

- src/components/organisms/todo-list/TodoList.tsx
- src/views/todo/todo-item/TodoItem.tsx
- src/views/todo/todo-item/action-icon/ActionIcon.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-191)
<br/>
- `router.push('${pathname}?todoId=${todo.id}');` 이렇게 추가했습니다.
-  미사용 코드 정리 
<br/>
> fix(TODO-191): 할 일 목록 - 노트 사이드바 오픈 시 pathname 추가

- src/hooks/todo/useCreateTodo.ts
- src/hooks/todo/useDeleteTodo.ts
- src/hooks/todo/useInfiniteTodo.ts
- src/hooks/todo/useUpdateTodo.ts
- src/hooks/useTodoListAction.tsx
- src/pages/todo/index.tsx
- src/views/todo/todo-create-form/TodoCreateForm.tsx
- src/views/todo/todo-update-form/TodoUpdateForm.tsx
- src/views/todo/todoPage/Todos.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-195)
<br/>
- 쿼리키 중복 고치면서 각 연관 훅에 무효화도 추가
- 할 일 생성/수정/삭제 시 **토스트 추가**도 했습니다.
- 토스트 추가한 훅을 사용하지 않던 페이지(모든 할 일 목록)도 훅 사용해서 정리
<br/>
- 정리나 추가한 코드는 급하지 않지만 서스펜스 적용으로 에러를 방지하기 위해 긴급라벨 달았습니다!
> fix(TODO-195): [할 일 목록 페이지] 무한스크롤 쿼리키 수정

- .github/workflows/storybook.yml
- .github/workflows/vercel-deploy.yml
- build.sh
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-193)
<br/>
- 프로젝트 배포 레포지토리에 동기화 시 숨김파일들이 모두 삭제되던 버그를 해결하였습니다.
- 스토리북 자동배포 워크플로우에 곧 만료되는 ubuntu 버전을 사용하여 발생하던 오류를 해결하였습니다.
<br/>
- 다른 PR들 merge 되기 전에 버그가 수정되어야 해서 urgent 붙였습니다 !
> fix(TODO-193): [CI/CD] 프로젝트 및 스토리북 배포 버그 해결

- src/components/atoms/skeleton/Skeleton.stories.tsx
- src/components/atoms/skeleton/Skeleton.tsx
- src/components/organisms/boundary-wrapper/BoundaryWrapper.tsx
- src/styles/globals.css
- src/styles/skeleton.css
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-194)
<br/>
- 에러바운더리 기능을 추가했습니다
- Errorboundary, Suspense의 default fallback이 있으며 커스텀해서 넣으셔도 됩니다.
- Skeleton을 추가했습니다.
사용법
```ts
// 기본 사용
<BoundaryWrapper>
<Component />
</BoundaryWrapper>
// 따로 fallback을 줄 경우
<BoundaryWrapper fallback={<div>로딩중...</div>} 
errorFallback={({ error }) => (<div>...{error.message}</div>)}>
<Component />
</BoundaryWrapper>
```
- 토스트는 잠깐 해봤는데 에러가 나네요 ㄷㄷ 낼 하겠습니다
> feat(TODO-194): 에러바운더리 기능 추가

- src/apis/noteApi.ts
- src/hooks/note/useCreateNote.ts
- src/hooks/note/useNoteDraft.ts
- src/hooks/note/useUpdateNote.ts
- src/views/note/note-drawer/NoteDrawer.tsx
- src/views/note/note-form/NoteCreationForm.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-189)
<br/>
- 노트 작성/수정 ErrorBoundary, Suspense 적용
- 노트 작성/수정 완료 후
- 토스트 처리
- 노트 상세보기 사이드바로 이동
- 관련 쿼리키 무효화
- NoteDrawer 에서 mode를 불필요한 상태 관리 대신 useMemo 처리
<br/>
> feat(TODO-189): [노트 작성/수정] 쿼리키 적용 및 에러, 로딩 리팩토링

- src/pages/login/index.tsx
- src/pages/signup/index.tsx
- src/views/sign/SignForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-202)
- 하단 링크에 간격을 두었습니다.
- smd 사이즈 레이아웃 추가했습니다.
- 폼 네이밍을 수정했습니다.
- 
-
> style(TODO-202): 로그인/회원가입 스타일 & 기타

- src/views/note/note-form/Editor.tsx
- src/views/note/note-form/EditorTextCounter.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- src/views/note/note-form/TitleCounter.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-201)
<br/>
- 노트 작성/수정 시 필수 입력 상태에 따라 버튼 disabled
- 에디터 UI 수정
- 제목 최대 글자 수 처리
- 본문 글자 수 오류 수정
<br/>
- 수정된 에디터 UI
> feat(TODO-201): [노트 작성/수정] 노트 작성/수정 일부 workflow 수정

- src/pages/login/index.tsx
- src/pages/signup/index.tsx
- src/views/sign/Main.tsx
- src/views/sign/SignForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-211)
<br/>
- max-width 값을 주었습니다.
-
> style(TODO-211): 로그인/회원가입 레이아웃 수정

- package.json
- pnpm-lock.yaml
- src/pages/_app.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-214)
<br/>
- 쿼리키 복잡도가 증가함에 따라 Devtools의 필요성이 느껴져 설치하였습니다.
<br/>
- 정말 유용할 겁니다....
> chore(TODO-214): [라이브러리 설치] Tanstack Query Devtools 설치

- src/apis/note/fetchNotes.ts
- src/views/notes/note-list/NoteList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-222)
<br/>
- MVP 피드백 반영하였습니다.
- interface 네이밍 대문자로 수정
- 노트 리스트의 각 아이템마다 key값 부여
<br/>
> chore(TODO-222): [노트 모아보기] interface 대문자로 수정, 컴포넌트 key값 부여

- src/hooks/todo/useProgressTodo.ts
- src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
- src/views/dashboard/goal-based-todo/components/ProgressBar.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-216)
<br/>
- 프로그래스바 API 연동하였습니다.
- 자세히보기 클릭 시 목표 상세페이지로 이동하도록 하였습니다. 
https://github.com/user-attachments/assets/a66bd874-2e3c-4b88-852f-fb703a82aa2f
<br/>
> feat(TODO-216): [대시보드/목표별 할 일] 프로그래스바, 자세히보기 기능 구현

- src/components/organisms/todo-list/TodoList.tsx
- src/contexts/InputModalContext.tsx
- src/pages/dashboard/index.tsx
- src/pages/todo/index.tsx
- src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
- src/views/goal/todo/GoalTodoContainer.tsx
- src/views/layouts/sidebar/components/MenuDashBoard.tsx
- src/views/note/note-form/Editor.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/todo/TodoForm.stories.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-229)
<br/>
- `type ModalType = "createTodo" | "updateTodo" | "link" | null;` 모달 타입 확실히 구분
<br/>
- 모달 수리 미루려 했는데 이렇게 시작하네요 우하하
> refactor(TODO-229): inputModal 폼 타입 설정

- src/hocs/AuthLayer.tsx
- src/pages/_app.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-233)  
- 전역으로 설정된 AuthLayer의 Suspense 제거
- 패치 시 발생되는 스피너 제거
- 파일 위치가 이상하여 변경
-
> hotfix(TODO-233): 인증레이어 수정, 위치 변경

- src/views/note/note-detail/NoteDetail.tsx
- src/views/note/note-detail/components/LinkItem.tsx
- src/views/note/note-detail/components/NoteDetailContent.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-246)
<br/>
- 링크가 길어질 때 깨지는 UI 수정
- 내용이 길어져 스크롤 바가 화면을 넘어가면 보이지 않는 UI 수정
<br/>
> style(TODO-246): [노트 상세] 레이아웃, 링크 스타일 수정

- src/hooks/goal/useCreateGoal.ts
- src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-249)
<br/>
- queryKey를 추가하여서 낙관적 업데이트를 비관적 업데이트로 변경
- 무한 스크롤에서 불필요한 변수 제거
<br/>
> fix(TODO-249): [목표 생성] 낙관적 업데이트 제거 후 비관적 업데이트 적용

- src/components/molecules/error-fallback/ErrorFallback.tsx
- src/pages/_app.tsx
- src/views/note/note-form/GoalTodoDisplay.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-251)
<br/>
- ErrorFallback 텍스트 스타일 지정
- 노트 작성/수정 todo title 텍스트 스타일 지정
- _app.tsx 의 main 태그로 감싸진 부분을 div로 수정
<br/>
- 폰트는 정말 못알아차리겠던데 매의 눈 부럽습니다🤩
> style(TODO-251): 적용되지 않았던 텍스트 스타일 지정 및 _app.tsx main 태그 수정

- src/views/layouts/sidebar/components/MenuDashBoard.tsx
- src/views/note/note-form/LinkModal.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-252)
<br/>
- 사이드바의 할일 생성 모달에 대한 조건문 추가
- 노트 작성/수정의 링크 업로드 모달에 대한 조건문 추가
<br/>
> fix(TODO-252): [사이드바, 노트 작성/수정] 할 일 생성 모달 및 링크 업로드 모달 생성 조건문 추가

- src/apis/todoApi.ts
- src/hooks/todo/useCreateTodo.ts
- src/hooks/todo/useDeleteTodo.ts
- src/hooks/todo/useProgressTodo.ts
- src/hooks/todo/useTodos.ts
- src/hooks/todo/useUpdateTodo.ts
- src/views/note/note-form/NoteCreateForm.tsx
- src/views/todo/todo-update-form/TodoUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-223)
<br/>
- 컨벤션에 맞춰 코드 통합
<br/>
> refactor(TODO-223): 할일 요청 todoApi 정리

- src/hooks/note/useBlockNavigation.ts
- src/views/note/note-drawer/NoteDrawer.tsx
- src/views/note/note-form/NoteForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-256)
<br/>
- 목표 상세 페이지에서 노트 작성/수정 중 페이지 이동 팝업 선택 후 발생하던 오류 처리
- 노트 작성/수정 완료 후 페이지 이동 팝업 뜨는 오류 처리
<br/>
> fix(TODO-256): [노트 수정/작성] 작성 중 페이지 이동 오류 처리

- package.json
- pnpm-lock.yaml
- src/apis/todoApi.ts
- src/hooks/auth/useSign.ts
- src/hooks/goal/useCreateGoal.ts
- src/hooks/goal/useDeleteGoal.ts
- src/hooks/goal/useFetchGoal.ts
- src/hooks/goal/useInfiniteGoals.ts
- src/hooks/goal/useUpdateGoal.ts
- src/hooks/note/useCreateNote.ts
- src/hooks/note/useDeleteNote.ts
- src/hooks/note/useFetchNote.ts
- src/hooks/note/useInfiniteNotes.ts
- src/hooks/note/useUpdateNote.ts
- src/hooks/todo/useCreateTodo.ts
- src/hooks/todo/useDeleteTodo.ts
- src/hooks/todo/useInfiniteTodo.ts
- src/hooks/todo/useProgressTodo.ts
- src/hooks/todo/useTodos.ts
- src/hooks/todo/useUpdateTodo.ts
- src/hooks/user/useFetchUser.ts
- src/pages/dashboard/index.tsx
- src/query-keys/goalQueryKeys.ts
- src/query-keys/index.ts
- src/query-keys/noteQueryKeys.ts
- src/query-keys/query-keys.md
- src/query-keys/todoQueryKeys.ts
- src/query-keys/userQueryKeys.ts
- src/views/note/note-form/NoteCreateForm.tsx
- src/views/todo/todo-update-form/TodoUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-235)
<br/>
TanStack Query에서 쿼리 키를 효율적으로 관리하기 위해 **쿼리 키 팩토리 패턴**을 적용하였습니다.
- 쿼리 키 구조화 및 일관된 네이밍 규칙 정립
- 기존에 하드코딩된 쿼리 키 모두 수정
- 쿼리 키 구조 설명 문서 작성  
<br/>
| **쿼리키 그룹** | **설명**         | **쿼리키**                                                   | **사용 예시**                                                   |
| --------------- | ---------------- | ------------------------------------------------------------ | --------------------------------------------------------------- |
| **note**        | 노트 무한스크롤  | ["note", "infinite", {"goalId": goalId}]                     | queryKeys.note.infinite(goalId: 123).queryKey                   |
|                 | 단일 노트        | ["note", "detail", {"noteId": noteId}]                       | …
> refactor(TODO-235): [쿼리 키 구조화] 쿼리 키 팩토리 적용

- src/hooks/todo/useFetchTodo.ts
- src/pages/_app.tsx
- src/views/note/note-drawer/NoteDrawer.tsx
- src/views/note/note-form/GoalTodoDisplay.tsx
- src/views/note/note-form/NoteCreateForm.tsx
- src/views/note/note-form/NoteForm.tsx
- src/views/note/note-form/NoteUpdateForm.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-261)
<br/>
- useFetchTodo hooks 분리 및 구조화된 쿼리키 적용
- NoteDetail 을 NoteDrawer 내부로 이동
- GoalTodoDisplay에 필요한 데이터 props 방식 대신 react-hook-form 방식으로 변경
<br/>
> refactor(TODO-261): [노트] 작성/수정 구조 리팩토링 및 쿼리키 구조화 적용

- src/views/todo/input-dropdown/InputDropdown.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-254)
<br/>
- 드롭다운 아이템s 최소 높이 지정했던 걸 그냥 뺐습니다.
- "등록된 목표가 없습니다" 항목으로 알림
- 스토리북에서도 확인 가능합니다
<br/>
> style(TODO-254): 할일폼 목표드롭다운 목표 없을 때

- src/apis/canEmbedApi.ts
- src/hooks/note/useCanEmbed.ts
- src/pages/api/check-iframe.tsx
- src/query-keys/embedQueryKeys.ts
- src/query-keys/index.ts
- src/query-keys/query-keys.md
- src/views/note/note-detail/components/EmbeddedContent.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-180)
<br/>
- 노트상세 사이드바에서 임베드 거부된 사이트에 바로가기 버튼을 표시
<br/>
<br/>
> feat(TODO-180): [노트 상세] 임베드 거부된 사이트 예외처리

- src/views/todo/todo-item/action-dropdown/TodoActionDropdown.tsx
- src/views/todo/todo-item/action-icon/ActionIcon.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-278)
<br/>
- ActionIcon 리팩토링: 인라인 콜백함수 정리, 컴포넌트 분리
<br/>
> refactor(TODO-278): 할일 목록 드롭다운 분리, useEffect 제거

- src/pages/dashboard/index.tsx
- src/views/dashboard/recent-todo/RecentTodo.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-279)
<br/>
- 최근 할 일 로딩 시 레이아웃 밀림현상으로 인하여 레이아웃 위치만 변경했습니다..!
- 
<br/>
> style(TODO-279): [대시보드] 최근 할 일 로딩 레이아웃 위치 수정

- src/views/note/note-detail/NoteDetail.tsx
- src/views/note/note-detail/components/ActionBtns.tsx
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-271)
<br/>
- 노트상세 사이드바에서 수정, 삭제 버튼 디자인 변경하였습니다.
https://github.com/user-attachments/assets/bfefc21f-6996-4811-805d-b80e68dc19d9
<br/>
> style(TODO-271): [노트상세] 수정, 삭제 버튼 디자인 변경

- src/hooks/note/useAutoSaveNoteDraft.ts
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-281)
<br/>
- 5분 자동 저장 시 빈 노트일 경우 임시 저장 토스트 문구 나타나지 않도록 변경
<br/>
> refactor(TODO-281): [노트 작성/수정] 자동 임시 저장 로직 리팩토링

- .github/workflows/codecov.yml
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-284)
<br/>
- 테스트 커버리지 확인을 위한 codecov 워크플로우 구축하였습니다.
- 이번 PR이 main에 병합된 이후, 다음 PR부터 codecov에 테스트코드 연동됩니다.
<br/>
> chore(TODO-284) codecov 워크플로우 세팅

- README.md
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-283)
<br/>
- 리드미에 페이지별 영상 추가하였습니다.
<br/>
> docs(TODO-283): 리드미에 페이지별 영상 추가

- README.md
- [연관된 이슈 링크](https://quesddo.atlassian.net/browse/TODO-283)
<br/>
- 리드미 토글 안되는 부분 수정하였습니다.
<br/>
> docs(TODO-283) 리드미 수정
